# Generated by Django 4.1 on 2025-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookproject_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproject',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('cancelled', 'Cancelled'), ('shipped', 'Shipped')], default='in_cart', max_length=20),
        ),
    ]
