# Generated by Django 4.1 on 2025-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproject',
            name='is_shipment_prepared',
            field=models.BooleanField(default=False),
        ),
    ]
