name: Deploy Backend to Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      
      - name: Navigate to backend directory
        run: cd fastprint-backend-main/fastprint-backend-main
      
      - name: Install dependencies
        working-directory: ./fastprint-backend-main/fastprint-backend-main
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Django checks
        working-directory: ./fastprint-backend-main/fastprint-backend-main
        run: |
          python manage.py check
        continue-on-error: true
      
      - name: Run migrations check
        working-directory: ./fastprint-backend-main/fastprint-backend-main
        run: |
          python manage.py makemigrations --check --dry-run
        continue-on-error: true

  deploy:
    name: Deploy to Server
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            # Navigate to project directory
            cd ~/Fastprint-Fast/fastprint-backend-main/fastprint-backend-main
            
            # Pull latest changes
            git pull origin main
            
            # Activate virtual environment
            source venv/bin/activate
            
            # Install/update dependencies
            pip install -r requirements.txt
            
            # Run database migrations
            python manage.py migrate --noinput
            
            # Collect static files
            python manage.py collectstatic --noinput
            
            # Restart PM2 process
            pm2 restart fastprint-backend
            
            # Save PM2 process list
            pm2 save
            
            # Display PM2 status
            pm2 list
      
      - name: Verify Deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            # Check if the application is running
            pm2 show fastprint-backend
            
            # Check logs for any errors
            pm2 logs fastprint-backend --lines 50 --nostream
      
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Backend deployment successful!"
          else
            echo "❌ Backend deployment failed!"
          fi
